 const words:any ={
  "aag": "Indicates the presence of fire or flames which may rapidly spread and pose a serious threat to human life and nearby property.",
  "dhuaan": "Smoke detected in the environment, often an early indicator of fire or hazardous burning materials.",
  "blast": "A sudden explosive event has occurred, potentially causing structural damage and human casualties.",
  "visphot": "An explosion involving high energy release, posing extreme danger to nearby individuals.",
  "bomb": "Indicates a possible explosive device threat requiring immediate security and evacuation protocols.",
  "bomb dhamaka": "Confirms detonation of an explosive device resulting in high risk of casualties.",
  "gas": "Leakage of flammable or toxic gas detected, creating risk of suffocation, poisoning, or explosion.",
  "zahrili gas": "Presence of poisonous gas that can cause serious health damage or death upon inhalation.",
  "bhagadad": "A panic-driven crowd movement that can result in trampling, suffocation, and severe injuries.",
  "bhagdad": "A panic-driven crowd movement that can result in trampling, suffocation, and severe injuries.",
  "baghdad": "A panic-driven crowd movement that can result in trampling, suffocation, and severe injuries.",
  "stampede": "An uncontrolled crowd surge creating high risk of fatal injuries due to pressure and falls.",
  "bheed": "High concentration of people in a confined area, increasing risk of accidents and panic.",
  "bheed zyada hai": "Overcrowding beyond safe capacity, requiring crowd control or evacuation.",
  "gir": "An individual has fallen and may require medical assistance.",
  "gir rahe hain": "Multiple individuals are falling, indicating instability or crowd pressure.",
  "dab": "People are being crushed under crowd pressure or heavy objects, indicating life-threatening danger.",
  "phans": "Individuals are trapped and unable to escape from a dangerous situation.",
  "raasta band": "An evacuation or access route is blocked, limiting safe movement.",
  "darwaza band": "An emergency exit is inaccessible, increasing evacuation risk.",
  "current": "An electrical shock incident that may cause serious injury or fatality.",
  "bijli": "Exposure to live electrical current causing potential burns or cardiac arrest.",
  "wire": "Exposed electrical wiring creating electrocution and fire risk.",
  "pani": "Water accumulation detected which may indicate flooding or drainage failure.",
  "baadh": "Flooding situation posing danger to infrastructure and human safety.",
  "doob": "An individual is actively drowning and requires immediate rescue.",
  "doob gaye": "Confirmed drowning incident involving one or more individuals.",
  "roof": "Structural collapse of a roof posing severe injury or fatality risk.",
  "deewar gir": "Wall collapse detected, indicating structural instability.",
  "building gir": "Building shows signs of imminent collapse and must be evacuated.",
  "bhukamp": "Earthquake activity detected which may damage structures and cause injuries.",
  "hil": "Ground or structure shaking detected, possibly due to seismic activity.",
  "maar": "A fatal violent act has occurred requiring immediate law enforcement response.",
  "chaku": "Presence or use of a knife indicating a close-range violent threat.",
  "goli": "Gunfire detected indicating a life-threatening armed situation.",
  "firing": "Active shooting event with high casualty risk.",
  "hathiyar": "Weapon detected posing a potential threat to public safety.",
  "loot": "Robbery in progress involving force or intimidation.",
  "chori": "Unauthorized theft activity detected.",
  "daka": "Armed robbery involving coordinated criminal activity.",
  "hungama": "Public disorder causing fear, damage, or violence.",
  "riot": "Large-scale violent unrest involving groups or crowds.",
  "patharbaazi": "Stone throwing incident that may cause injuries and property damage.",
  "tod phod": "Deliberate destruction of public or private property.",
  "jagda": "Physical confrontation that may escalate into serious violence.",
  "peet": "Ongoing physical assault causing bodily harm.",
  "peeta": "Ongoing physical assault causing bodily harm.",
  "chot lagi": "An injury has occurred requiring medical evaluation.",
  "zakhmi": "An injured person is present at the scene.",
  "khoon beh raha": "Severe bleeding detected posing immediate life threat.",
  "behosh": "An unconscious individual requiring urgent medical attention.",
  "heart attack": "Suspected cardiac emergency requiring immediate medical response.",
  "saans nahi aa rahi": "Respiratory distress that can quickly become fatal.",
  "dam ghut raha": "Oxygen deprivation or suffocation risk detected.",
  "zeher": "Poison-related threat detected.",
  "zeher khaya": "Poison ingestion incident requiring emergency treatment.",
  "overdose": "Excessive drug intake posing serious health risk.",
  "ambulance bulao": "Urgent request for emergency medical transport.",
  "doctor bulao": "Immediate medical assistance requested.",
  "police bulao": "Law enforcement intervention requested.",
  "help": "General emergency assistance request.",
  "bachao": "Immediate rescue required to prevent harm.",
  "madad chahiye": "Urgent assistance requested due to danger.",
  "emergency": "A critical situation requiring immediate coordinated response.",
  "alert": "A warning signal indicating potential or active danger.",
  "warning": "Advance notice of a hazardous condition.",
  "evacuate": "Instruction to leave an area immediately for safety.",
  "khali karo": "Urgent evacuation order issued.",
  "bahar niklo": "Immediate exit required to avoid danger.",
  "andar mat jao": "Entry restricted due to unsafe conditions.",
  "unsafe": "Area does not meet safety standards.",
  "danger": "Immediate threat to safety detected.",
  "restricted": "Access limited for security or safety reasons.",
  "lockdown": "Movement restricted due to a serious threat.",
  "hostage": "Individuals are being forcibly detained.",
  "kidnap": "Abduction incident involving force or coercion.",
  "missing": "Someone is reported missing and may be in danger.",
  "lapata": "Missing person alert requiring search action.",
  "terror": "Terror-related activity posing mass casualty risk.",
  "attack": "A deliberate violent act against people or infrastructure.",
  "suspect": "A person displaying suspicious or potentially dangerous behavior.",
  "suspicious bag": "An unattended object that may contain hazardous material.",
  "panic": "Widespread fear causing loss of orderly behavior.",
  "chaos": "Severe breakdown of order increasing risk of injuries."
}
export default words